<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Motivación" data-toc-modified-id="Motivación-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Motivación</a></span><ul class="toc-item"><li><span><a href="#Bag-of-Words" data-toc-modified-id="Bag-of-Words-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Bag of Words</a></span></li><li><span><a href="#Word-Embeddings" data-toc-modified-id="Word-Embeddings-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Word Embeddings</a></span></li><li><span><a href="#Word2vec" data-toc-modified-id="Word2vec-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Word2vec</a></span><ul class="toc-item"><li><span><a href="#Skip-gram" data-toc-modified-id="Skip-gram-1.3.1"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>Skip-gram</a></span></li></ul></li><li><span><a href="#Detalles-del-Modelo" data-toc-modified-id="Detalles-del-Modelo-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Detalles del Modelo</a></span></li><li><span><a href="#La-capa-Oculta" data-toc-modified-id="La-capa-Oculta-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>La capa Oculta</a></span></li><li><span><a href="#Fuentes" data-toc-modified-id="Fuentes-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Fuentes</a></span></li></ul></li><li><span><a href="#Entrenar-nuestros-Embeddings" data-toc-modified-id="Entrenar-nuestros-Embeddings-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Entrenar nuestros Embeddings</a></span><ul class="toc-item"><li><span><a href="#Cargar-el-dataset-desde-el-archivo" data-toc-modified-id="Cargar-el-dataset-desde-el-archivo-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Cargar el dataset desde el archivo</a></span></li><li><span><a href="#Limpiar-las-noticias" data-toc-modified-id="Limpiar-las-noticias-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Limpiar las noticias</a></span><ul class="toc-item"><li><span><a href="#Comenzamos-el-preprocesamiento:" data-toc-modified-id="Comenzamos-el-preprocesamiento:-2.2.1"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span>Comenzamos el preprocesamiento:</a></span></li></ul></li></ul></li><li><span><a href="#Extracción-de-Frases" data-toc-modified-id="Extracción-de-Frases-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Extracción de Frases</a></span><ul class="toc-item"><li><span><a href="#Separamos-todos-los-documentos-en-tokens." data-toc-modified-id="Separamos-todos-los-documentos-en-tokens.-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Separamos todos los documentos en tokens.</a></span></li><li><span><a href="#Buscamos-bigramas-relevantes" data-toc-modified-id="Buscamos-bigramas-relevantes-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Buscamos bigramas relevantes</a></span></li><li><span><a href="#Retokenizar-el-corpus" data-toc-modified-id="Retokenizar-el-corpus-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Retokenizar el corpus</a></span></li></ul></li><li><span><a href="#Entrenamiento-del-Modelo" data-toc-modified-id="Entrenamiento-del-Modelo-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Entrenamiento del Modelo</a></span><ul class="toc-item"><li><span><a href="#Construir-el-vocabulario" data-toc-modified-id="Construir-el-vocabulario-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Construir el vocabulario</a></span></li><li><span><a href="#Entrenar-el-Modelo" data-toc-modified-id="Entrenar-el-Modelo-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Entrenar el Modelo</a></span></li><li><span><a href="#Guardar-y-cargar-el-modelo" data-toc-modified-id="Guardar-y-cargar-el-modelo-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Guardar y cargar el modelo</a></span></li></ul></li><li><span><a href="#Tareas:-Palabras-mas-similares-y-Analogías" data-toc-modified-id="Tareas:-Palabras-mas-similares-y-Analogías-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Tareas: Palabras mas similares y Analogías</a></span><ul class="toc-item"><li><span><a href="#Palabras-mas-similares" data-toc-modified-id="Palabras-mas-similares-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Palabras mas similares</a></span></li></ul></li><li><span><a href="#Analogías" data-toc-modified-id="Analogías-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Analogías</a></span></li><li><span><a href="#Visualizar" data-toc-modified-id="Visualizar-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Visualizar</a></span></li><li><span><a href="#Visualizamos" data-toc-modified-id="Visualizamos-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Visualizamos</a></span></li><li><span><a href="#Word-Embeddings-como-características-para-clasificar" data-toc-modified-id="Word-Embeddings-como-características-para-clasificar-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Word Embeddings como características para clasificar</a></span><ul class="toc-item"><li><span><a href="#Dividimos-el-dataset-de-embeddings-en-training-y-test" data-toc-modified-id="Dividimos-el-dataset-de-embeddings-en-training-y-test-9.1"><span class="toc-item-num">9.1&nbsp;&nbsp;</span>Dividimos el dataset de embeddings en training y test</a></span></li><li><span><a href="#Entrenamos-el-clasificador" data-toc-modified-id="Entrenamos-el-clasificador-9.2"><span class="toc-item-num">9.2&nbsp;&nbsp;</span>Entrenamos el clasificador</a></span></li><li><span><a href="#Predecimos-y-evaluamos:" data-toc-modified-id="Predecimos-y-evaluamos:-9.3"><span class="toc-item-num">9.3&nbsp;&nbsp;</span>Predecimos y evaluamos:</a></span></li></ul></li><li><span><a href="#En-comparación-con-BoW" data-toc-modified-id="En-comparación-con-BoW-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>En comparación con BoW</a></span></li></ul></div>

# Auxiliar 2 - Word Embeddings


La clase auxiliar de esta semana tendrá varios objetivos: 

- Entender lo básico de word embeddings 
- Entrenar nuestros propios `word embeddings` usando el dataset de noticias de la radio biobio. 
- Experimentar y visualizar los embeddings entrenados. 
- Por último, resolver la misma tarea de topic classification de la clase auxiliar 1, pero usando los embeddings que hemos calculado. 



## Motivación

### Bag of Words

Pensemos en estas 2 frases como documentos (dieciocheros 🥟🥟🍷):

    ¡Estuvo buena esa empanada !
    ¡Estuvo espectacular esa empanada!

En la practica, sabemos que significan lo mismo.


Supongamos que queremos ver que tan similares son ambos documentos. 
Para esto, generamos un modelo `Bag of Words` sobre cada documento (es decir, transformamos cada palabra a un vector one-hot):

$$v = \{estuvo, buena, esa, empanada, espectacular\}$$

Entonces, el doc 1 quedará:

$$\begin{bmatrix}1 \\ 0 \\ 0 \\ 0 \\ 0\end{bmatrix} + \begin{bmatrix}0 \\ 1 \\ 0 \\ 0 \\ 0\end{bmatrix} + \begin{bmatrix}0 \\ 0 \\ 1 \\ 0 \\ 0\end{bmatrix} + \begin{bmatrix}0 \\ 0 \\ 0 \\ 1 \\ 0\end{bmatrix} = \begin{bmatrix}1 \\ 1 \\ 1 \\ 1 \\ 0\end{bmatrix}$$

Y el doc 2 quedará:

$$\begin{bmatrix}1 \\ 0 \\ 0 \\ 0 \\ 0\end{bmatrix} + \begin{bmatrix}0 \\ 0 \\ 0 \\ 0 \\ 1\end{bmatrix} + \begin{bmatrix}0 \\ 0 \\ 1 \\ 0 \\ 0\end{bmatrix} + \begin{bmatrix}0 \\ 0 \\ 0 \\ 1 \\ 0\end{bmatrix} = \begin{bmatrix}1 \\ 0 \\ 1 \\ 1 \\ 1\end{bmatrix}$$


**¿Cuál es el problema?**

`buena` $\begin{bmatrix}0 \\ 0 \\ 0 \\ 0 \\ 1\end{bmatrix}$ y `espectacular` $ \begin{bmatrix}0 \\ 1 \\ 0 \\ 0 \\ 0\end{bmatrix}$ representan en la práctica lo mismo, 

pero en esta representación **son totalmente distintos**, ya que ocupan distintas dimensiones en el modelo. Esto hace que en la práctica, que `buena` y `espectacular` sean tan distintas como `estuvo` y `empanada`. Esto evidentemente, repercute en la calidad de los modelos que creamos.


Nos gustaría que eso no sucediera. Que existiera algún método que nos permitiera hacer que palabras similares tengan representaciones similares...


### Word Embeddings

Pensemos un poco en la `hipótesis distribucional`. Esta plantea que:

    "palabras que ocurren en similares contextos tienden a tener significados similares" 

¿Podríamos crear algúna representación vectorial que capture los contextos de las palabras? - La respuesta es si. Estos son los **Word Embeddings**. 

La idea principal de Word Embeddings (O *Word vectors*) es basarse en la hipotesis distribuciónal para crear, por cada palabra del vocabulario, representaciones vectoriales continuas que capturen su contexto.


Es decir, en nuestro ejemplo, `buena` y `espectacular` ocurren en el mismo contexto, por lo que los word embeddings que los deberían representan deberían ser muy similares (ejemplos de mentira hechos a mano*):

`buena` $\begin{bmatrix}0.32 \\ 0.44 \\ 0.92 \\ .001 \end{bmatrix}$ y `espectacular` $\begin{bmatrix}0.30 \\ 0.50 \\ 0.92 \\ .002 \end{bmatrix}$ versus `empanada`  $\begin{bmatrix}0.77 \\ 0.99 \\ 0.004 \\ .1 \end{bmatrix}$ el cuál es claramente distinto.


Pero, **¿Cómo capturamos el contexto dentro de nuestros vectores?**


###  Word2vec

Word2Vec es una de las herramientas que nos permitiran construir estos vectores. Consiste en entrenar una **red neuronal de solo 1 capa oculta** a través de la resolución de una task auxiliar: `Skip-Gram`

¿Por qué auxiliar?: Porque la usaremos solo para entrenar los pesos de la capa oculta de red. Una vez entrenada, nunca mas haremos Skip-Gram!. 

#### Skip-gram

En pocas palabras, la task a resolver es la siguiente: 

- Toma una oración cualquiera del corpus. 

- Dada una palabra cualquiera en la oración, mira las palabras cercanas a esta (dentro de una ventana definida) y toma una aleatoria. 

- La red deberá predecir que tan probable es que esta palabra sea cercana a la palabra que escogimos.


Por ejemplo, para la típica frase: 

     “The quick brown fox jumps over the lazy dog.”
     
Usando una ventana de 2 palabras, tendremos: 

![Skip Gram](http://mccormickml.com/assets/word2vec/training_data.png)

Esto es lo que luego usará la red para aprender las relaciones entre las palabras.

### Detalles del Modelo


Pensemos por ejemplo, en un paso del entrenamiento: 

El vector de entrada será un One-hot de la palabra que estemos viendo en ese momento. En este caso, `ants`.

La red, usando su capa oculta, nos entregará la probabilidad de la que la palabra que estamos viendo aparezca con respecto a cada palabra del vocabulario.


![Skip Gram](http://mccormickml.com/assets/word2vec/skip_gram_net_arch.png)

Nota: Esto es computacionalmente una locura, ya que por cada palabra debemos calcular la probabilidad de aparición de todas las otras. Imaginen el caso de un vocabulario de 10 millones de palabras...
En clases se verá como se puede hacer esto de forma eficiente.

Por ende, la salida será un vector que representará una distribución de probabilidades. 

Durante el entrenamiento, dicho vector será comparado con las estadísticas reales de co-ocurrencia de las palabras.

### La capa Oculta

Al terminar el entrenamiento, ¿Qué nos queda en la capa oculta?

Básicamente, una matriz de $v$ filas por $300$ columnas, la cual contiene lo que buscabamos: Una representación continua de todas las palabras de nuestro vocabualrio.  

**Cada fila de la matriz es un vector que contiene la representación continua una palabra del vocabulario.**


![Capa Oculta](http://mccormickml.com/assets/word2vec/word2vec_weight_matrix_lookup_table.png)

¿Cómo la usamos eficientemente?

Simple: usamos los mismos vectores one-hot del BoW y las multiplicamos por la matriz:

![Capa Oculta](http://mccormickml.com/assets/word2vec/matrix_mult_w_one_hot.png)


### Fuentes

Word2vec:
- mccormickml.com/2016/04/19/word2vec-tutorial-the-skip-gram-model/
- https://towardsdatascience.com/introduction-to-word-embedding-and-word2vec-652d0c2060fa

Gensim: 
- https://www.kaggle.com/pierremegret/gensim-word2vec-tutorial

Nota: Todas las imagenes pertenecen a [Chris McCormick](http://mccormickml.com/about/)


## Entrenar nuestros Embeddings

Para entrenar nuestros embeddings, usaremos el paquete gensim. Este trae una muy buena implementación de `word2vec`.




In [1]:
import re  
import pandas as pd 
from time import time  
from collections import defaultdict 
import string 
import multiprocessing
import os
import requests

# spacy
import spacy 

# word2vec
from gensim.models import Word2Vec, KeyedVectors
from gensim.models.phrases import Phrases, Phraser

import logging  # Setting up the loggings to monitor gensim
logging.basicConfig(format="%(levelname)s - %(asctime)s: %(message)s", datefmt= '%H:%M:%S', level=logging.INFO)

# scikit-learn
from sklearn.manifold import TSNE
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer  
from sklearn.metrics import confusion_matrix
from sklearn.utils.multiclass import unique_labels

# visualizaciones
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
from ipywidgets import widgets

# Cargar modelos de spacy en español.
nlp = spacy.load("es_core_news_sm",  disable=["tagger", "parser", "ner"])

C:\Users\pablo\Miniconda3\envs\pytorch\lib\site-packages\gensim\utils.py:1197: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


### Cargar el dataset desde el archivo

Nota: Pandas descomprime por si mismo el archivo bz2. Pueden descomprimirlo manualmente usando 7zip.

In [2]:
data = pd.read_json(
    'https://github.com/dccuchile/CC6205/releases/download/Data/biobio_clean.bz2',
    encoding="utf-8")

**Examinemos un par de ejemplos**

In [3]:
data.sample(2)

author               author_link  \
22459   Valentina González  /lista/autores/vgonzalez   
22415  César Vega Martínez     /lista/autores/cevega   

                                                   title  \
22459  Juez de Garantía de Temuco presenta demanda in...   
22415  Rosa Bernile Nienau: así fue la cálida amistad...   

                                                    link  category  \
22459  https://www.biobiochile.cl/noticias/nacional/r...  nacional   
22415  https://www.biobiochile.cl/noticias/sociedad/m...  sociedad   

                  subcategory  \
22459  region-de-la-araucania   
22415               misterios   

                                                 content  \
22459    Una demanda indemnizatoria en contra del fis...   
22415    Fue en noviembre pasado cuando la casa de su...   

                                                    tags  \
22459  [#Demanda, #Juez de Garantía, #Luis Olivares A...   
22415  [#Adolf Hitler, #Amistad, #borman, #Fotos, #ho...   

                                          embedded_links  publication_datetime  
22459  [https://media.biobiochile.cl/wp-content/uploa...         1564774560000  
22415                                                 []         1549106040000

### Limpiar las noticias

Primero, vamos a definir la función que definirá como será limpiado y tokenizado cada documento:

In [4]:
def cleaning(doc):
    # Tokenizar y remover  stopwords
    txt = [token.text for token in doc if not token.is_stop]

    if len(txt) > 2:
        return ' '.join(txt)

Observación:  `Word2Vec` usa el contexto de las oraciones para aprender las representaciones de las palabras.
Si la oración es muy pequeña, entonces, el entrenamiento no podrá inferir nada. Por eso, se retorna la oración solo cuando hay mas de 2 palabras dentro de la oración.




#### Comenzamos el preprocesamiento:

Primero convertimos todas las palabras del documento en minúsculas y realizamos una limpieza rápida de símbolos y espacios extras:

In [5]:
pre_cleaned_docs = (re.sub(r'[^\w\s+]', '', str(row)).lower() for row in data.content)

Ahora, tokenizamos el texto usando la función que definimos unas celdas mas arriba:

In [6]:
txt = [cleaning(doc) for doc in nlp.pipe(pre_cleaned_docs, batch_size=5000, n_threads=-1)]

In [7]:
print("Ejemplo de texto procesado:\n\n{}".format(txt[0]))

Ejemplo de texto procesado:

   noticia desarrollo   recopilando antecedentes noticia quédate atento a actualizaciones     estructura restante casa cayó valparaíso colapsó mañana miércoles   produjo a 1015 esquina aldunate huito murieron personas   información preliminar rescatistas labores suspendido peligro seguir trabajando habría lesionados  


Por último, almacenamos los documentos tokenizados en un `DataFrame` y eliminamos vacios/ducplicados

In [8]:
df_clean = pd.DataFrame({'clean': txt})
df_clean = df_clean.dropna().drop_duplicates()
df_clean.shape

(26265, 1)

## Extracción de Frases

Para crear buenas representaciones, es necesario tambien encontrar conjuntos de palabras que por si solas no tengan mayor significado (como `nueva` y `york`), pero que juntas que representen ideas concretas (`nueva york`). 

Para esto, usaremos el primer conjunto de herramientas de `gensim`: `Phrases` y `Phraser`.


### Separamos todos los documentos en tokens.


In [9]:
sent = [row.split() for row in df_clean['clean']] 

In [10]:
# para ver como quedan las noticias, quitar comentario a la siguiente linea:
sent[0]

['noticia',
 'desarrollo',
 'recopilando',
 'antecedentes',
 'noticia',
 'quédate',
 'atento',
 'a',
 'actualizaciones',
 'estructura',
 'restante',
 'casa',
 'cayó',
 'valparaíso',
 'colapsó',
 'mañana',
 'miércoles',
 'produjo',
 'a',
 '1015',
 'esquina',
 'aldunate',
 'huito',
 'murieron',
 'personas',
 'información',
 'preliminar',
 'rescatistas',
 'labores',
 'suspendido',
 'peligro',
 'seguir',
 'trabajando',
 'habría',
 'lesionados']

### Buscamos bigramas relevantes

Ahora, buscamos los bigramas relevantes dentro de nuesto corpus usando `Phrases`. La condición para que sean considerados es que aparezcan por lo menos 30 veces repetidas.


In [11]:
phrases = Phrases(sent, min_count=30, progress_per=5000) 

INFO - 11:43:34: collecting all words and their counts
INFO - 11:43:34: PROGRESS: at sentence #0, processed 0 words and 0 word types
INFO - 11:43:36: PROGRESS: at sentence #5000, processed 1095422 words and 759116 word types
INFO - 11:43:38: PROGRESS: at sentence #10000, processed 1923387 words and 1200422 word types
INFO - 11:43:40: PROGRESS: at sentence #15000, processed 2814795 words and 1627467 word types
INFO - 11:43:42: PROGRESS: at sentence #20000, processed 3801078 words and 2167896 word types
INFO - 11:43:44: PROGRESS: at sentence #25000, processed 4786655 words and 2672007 word types
INFO - 11:43:44: collected 2802254 word types from a corpus of 5045011 words (unigram + bigrams) and 26265 sentences
INFO - 11:43:44: using 2802254 counts as vocab in Phrases<0 vocab, min_count=30, threshold=10.0, max_vocab_size=40000000>


### Retokenizar el corpus

Por último, usando `Phraser`, re-tokenizamos el corpus con los bigramas encontrados



In [12]:
bigram = Phraser(phrases)
sentences = bigram[sent]

INFO - 11:43:44: source_vocab length 2802254
INFO - 11:44:12: Phraser built with 4039 4039 phrasegrams


In [13]:
# para ver como quedan las noticias retokenizadas, quitar comentario a la siguiente linea:
sentences[0]

['noticia',
 'desarrollo',
 'recopilando',
 'antecedentes',
 'noticia',
 'quédate',
 'atento',
 'a',
 'actualizaciones',
 'estructura',
 'restante',
 'casa',
 'cayó',
 'valparaíso',
 'colapsó',
 'mañana_miércoles',
 'produjo',
 'a',
 '1015',
 'esquina',
 'aldunate',
 'huito',
 'murieron',
 'personas',
 'información_preliminar',
 'rescatistas',
 'labores',
 'suspendido',
 'peligro',
 'seguir_trabajando',
 'habría',
 'lesionados']

## Entrenamiento del Modelo



Primero, como es usual, creamos el modelo. En este caso, usaremos uno de los primero modelos de embeddings neuronales: `word2vec`

Algunos parámetros importantes:

- `min_count`: Ignora todas las palabras que tengan frecuencia menor a la indicada
- `size` : El tamaño de los embeddings que crearemos. Por lo general, se utilizan 300
- `workers`: Cantidad de CPU que serán utilizadas en el entrenamiento

In [ ]:
biobio_w2v = Word2Vec(min_count=10,
                      window=2,
                      size=300,
                      sample=6e-5,
                      alpha=0.03,
                      min_alpha=0.0007,
                      negative=20,
                      workers=multiprocessing.cpu_count() - 1)

### Construir el vocabulario

Para esto, se creará un conjunto que contendrá (una sola vez) todas aquellas palabras que aparecen mas de `min_count` veces. 

In [ ]:
biobio_w2v.build_vocab(sentences, progress_per=5000)

### Entrenar el Modelo

A continuación, entenaremos el modelo. 
Los parámetros que usaremos serán: 

- `total_examples`: Número de documentos.
- `epochs`: Número de veces que se iterará sobre el corpus.



In [ ]:
t = time()
biobio_w2v.train(sentences, total_examples=biobio_w2v.corpus_count, epochs=30, report_delay=10)
print('Time to train the model: {} mins'.format(round((time() - t) / 60, 2)))

Ahora que terminamos de entrenar el modelo, le indicamos que no lo entrenaremos mas. 
Esto nos permitirá ejecutar eficientemente las tareas que realizaremos.

In [ ]:
biobio_w2v.init_sims(replace=True)

###  Guardar y cargar el modelo

Para ahorrar tiempo, usaremos un modelo preentrenado.

In [ ]:

# Si entrenaste el modelo y lo quieres guardar, descomentar el siguiente bloque.

"""
if not os.path.exists('./pretrained_models'):
    os.mkdir('./pretrained_models')
biobio_w2v.save('./pretrained_models/biobio_w2v.model')
"""

# cargar el modelo (si es que lo entrenaron desde local.)
#biobio_w2v = KeyedVectors.load("./pretrained_models/biobio_w2v.model", mmap='r')


In [16]:
# descargar el modelo desde github
def read_model_from_github(url):
    if not os.path.exists('./pretrained_models'):
        os.mkdir('./pretrained_models')

    r = requests.get(url)
    filename = url.split('/')[-1]
    with open('./pretrained_models/' + filename, 'wb') as f:
        f.write(r.content)
    return True


[
    read_model_from_github(file) for file in [
        'https://github.com/dccuchile/CC6205/releases/download/Data/biobio_w2v.model',
        'https://github.com/dccuchile/CC6205/releases/download/Data/biobio_w2v.model.trainables.syn1neg.npy',
        'https://github.com/dccuchile/CC6205/releases/download/Data/biobio_w2v.model.wv.vectors.npy'
    ]
]
# cargar el modelo (si es que lo entrenaron desde local.)
biobio_w2v = KeyedVectors.load("./pretrained_models/biobio_w2v.model", mmap='r')


INFO - 11:48:36: loading Word2VecKeyedVectors object from ./pretrained_models/biobio_w2v.model
C:\Users\pablo\Miniconda3\envs\pytorch\lib\site-packages\smart_open\smart_open_lib.py:398: UserWarning:

This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function

INFO - 11:48:36: loading wv recursively from ./pretrained_models/biobio_w2v.model.wv.* with mmap=r
INFO - 11:48:36: loading vectors from ./pretrained_models/biobio_w2v.model.wv.vectors.npy with mmap=r
INFO - 11:48:36: setting ignored attribute vectors_norm to None
INFO - 11:48:36: loading vocabulary recursively from ./pretrained_models/biobio_w2v.model.vocabulary.* with mmap=r
INFO - 11:48:36: loading trainables recursively from ./pretrained_models/biobio_w2v.model.trainables.* with mmap=r
INFO - 11:48:36: loading syn1neg from ./pretrained_models/biobio_w2v.model.trainables.syn1neg.npy with 

## Tareas: Palabras mas similares y Analogías

### Palabras mas similares

Tal como dijimos anteriormente, los embeddings son capaces de codificar toda la información contextual de las palabras en vectores.

Y como cualquier objeto matemático, estos pueden operados para encontrar ciertas propiedades. Tal es el caso de las  encontrar las palabras mas similares, lo que no es mas que encontrar los n vecinos mas cercanos del vector.  

In [18]:
biobio_w2v.wv.most_similar(positive=["perro"])

INFO - 11:48:51: precomputing L2-norms of word weight vectors


[('gato', 0.47238367795944214),
 ('cachorro', 0.45501261949539185),
 ('canino', 0.4421420991420746),
 ('felino', 0.4251091778278351),
 ('gatito', 0.4125193655490875),
 ('animal', 0.40201663970947266),
 ('perrita', 0.39842987060546875),
 ('zorro', 0.39238905906677246),
 ('mascota', 0.39086073637008667),
 ('perros', 0.38970085978507996)]

In [19]:
biobio_w2v.wv.most_similar(positive=["trump"])

[('donald_trump', 0.6679385304450989),
 ('casa_blanca', 0.6449583768844604),
 ('unidos', 0.6023310422897339),
 ('washington', 0.5866063833236694),
 ('mandatario_estadounidense', 0.5600548386573792),
 ('presidente_donald', 0.5553752183914185),
 ('presidente_estadounidense', 0.5523015856742859),
 ('inquilino', 0.5197651386260986),
 ('unidos_donald', 0.5129491686820984),
 ('sessions', 0.5118564367294312)]

In [20]:
biobio_w2v.wv.most_similar(positive=["revolución"])

[('fidel_castro', 0.382219135761261),
 ('1959', 0.3599476218223572),
 ('islámica', 0.35400423407554626),
 ('marxismo', 0.3403622508049011),
 ('sandinista', 0.3341415524482727),
 ('1979', 0.31937718391418457),
 ('transformación', 0.31889623403549194),
 ('1917', 0.3090049624443054),
 ('burguesía', 0.30192387104034424),
 ('yucatán', 0.29723119735717773)]

In [21]:
biobio_w2v.wv.most_similar(positive=["revolución_democrática"])

[('pablo_vidal', 0.6696338057518005),
 ('orsini', 0.639187216758728),
 ('jorge_brito', 0.6381471157073975),
 ('frenteamplista', 0.6183565855026245),
 ('rd', 0.6119238138198853),
 ('prd', 0.598182201385498),
 ('demócratacristiano', 0.5970538258552551),
 ('maite', 0.5770610570907593),
 ('vlado', 0.5761114954948425),
 ('partido_democracia', 0.5688214302062988)]

In [22]:
biobio_w2v.wv.most_similar(positive=["pizza"])

[('hut', 0.6154688000679016),
 ('hamburguesas', 0.4615939259529114),
 ('corner', 0.4598219394683838),
 ('sandwich', 0.4314725399017334),
 ('autoservicio', 0.42904579639434814),
 ('repartidor', 0.4275974631309509),
 ('cafeterías', 0.42377257347106934),
 ('ekono', 0.4233115315437317),
 ('vodka', 0.4229376018047333),
 ('comida_rápida', 0.4187615215778351)]

In [23]:
biobio_w2v.wv.most_similar(positive=["uber"])

[('cabify', 0.5361112952232361),
 ('eats', 0.49480363726615906),
 ('beat', 0.4774724245071411),
 ('transporte_pasajeros', 0.4051392078399658),
 ('rappi', 0.38707831501960754),
 ('didi', 0.3694966435432434),
 ('vtc', 0.3587350845336914),
 ('aplicaciones', 0.35364559292793274),
 ('glovo', 0.35351526737213135),
 ('taxi', 0.3341372013092041)]

In [24]:
biobio_w2v.wv.most_similar(positive=["huawei"])

[('gigante_chino', 0.5173695087432861),
 ('zte', 0.5074669122695923),
 ('directora_financiera', 0.4465712308883667),
 ('5_g', 0.4312366247177124),
 ('china', 0.4225515127182007),
 ('meng_wanzhou', 0.4068417549133301),
 ('pekin', 0.38649022579193115),
 ('telecomunicaciones', 0.38293468952178955),
 ('teléfonos_inteligentes', 0.3672794699668884),
 ('chips', 0.36506158113479614)]

In [25]:
biobio_w2v.wv.most_similar(positive=["tvn"])

[('canal_13', 0.4343094825744629),
 ('mega', 0.36687153577804565),
 ('presidente_directorio', 0.3579253554344177),
 ('matinal', 0.3533702492713928),
 ('cuprífera', 0.336997389793396),
 ('directorio', 0.3351971507072449),
 ('orrego', 0.3331133723258972),
 ('fesur', 0.3310084342956543),
 ('rapu', 0.3075915575027466),
 ('comisión_investigadora', 0.3052249550819397)]

In [26]:
biobio_w2v.wv.most_similar(positive=["mapuches"])

[('intelectualmente', 0.5410281419754028),
 ('comuneros', 0.5132812857627869),
 ('pehuenches', 0.4597381353378296),
 ('comunidades_mapuches', 0.44987913966178894),
 ('mapuche', 0.4347573518753052),
 ('aucán', 0.4004420042037964),
 ('pehuenche', 0.37423285841941833),
 ('vecinales', 0.3617860972881317),
 ('ancestrales', 0.3590352535247803),
 ('hortaliceras', 0.35829445719718933)]

In [27]:
biobio_w2v.wv.most_similar(positive=["catrillanca"])

[('camilo_catrillanca', 0.5488350987434387),
 ('comunero_mapuche', 0.5073081254959106),
 ('comunero', 0.4860221743583679),
 ('único_imputado', 0.4092996120452881),
 ('chadwick', 0.3861224055290222),
 ('causa_derivada', 0.3794987201690674),
 ('tokman', 0.36469513177871704),
 ('sambuceti', 0.364555686712265),
 ('luchsinger', 0.35905542969703674),
 ('causándole', 0.3463499844074249)]

In [28]:
biobio_w2v.wv.most_similar(positive=["universidad_chile"])

[('magíster', 0.47122281789779663),
 ('universidad_santiago', 0.4577624201774597),
 ('universidad_concepción', 0.43267691135406494),
 ('odontología', 0.4286888837814331),
 ('agronomía', 0.4259319305419922),
 ('universidad_católica', 0.41985636949539185),
 ('mba', 0.4132372736930847),
 ('federación_estudiantes', 0.4114116430282593),
 ('facultad_ciencias', 0.37800729274749756),
 ('universidad_andrés', 0.377147912979126)]

In [29]:
biobio_w2v.wv.most_similar(positive=["ultraderechista"])

[('ultraderecha', 0.5372439622879028),
 ('extrema_derecha', 0.506591260433197),
 ('jair_bolsonaro', 0.4804544150829315),
 ('fascismo', 0.45208853483200073),
 ('antiinmigración', 0.452001690864563),
 ('ultraderechista_liga', 0.45156916975975037),
 ('excapitán_ejército', 0.444217324256897),
 ('interior_matteo', 0.4428623914718628),
 ('matteo_salvini', 0.43859899044036865),
 ('marine_pen', 0.4377690553665161)]

In [30]:
biobio_w2v.wv.most_similar(positive=["pinochet"])

[('augusto_pinochet', 0.4894692301750183),
 ('19761983', 0.3469034433364868),
 ('nostálgico', 0.3454264998435974),
 ('stroessner', 0.3346376419067383),
 ('franquista', 0.3176833987236023),
 ('fascista', 0.31446966528892517),
 ('torturador', 0.31268107891082764),
 ('19641985', 0.30675196647644043),
 ('anastasio', 0.3066090941429138),
 ('exdictador', 0.30496591329574585)]

In [31]:
biobio_w2v.wv.most_similar(positive=["serena"])

[('vilos', 0.46391141414642334),
 ('coquimbo', 0.4321473240852356),
 ('santiago', 0.4237024188041687),
 ('valle_elqui', 0.40091782808303833),
 ('pica', 0.3972700834274292),
 ('ovalle', 0.3957822620868683),
 ('puerto_natales', 0.3800183832645416),
 ('balmaceda', 0.3758486211299896),
 ('chillán', 0.37579774856567383),
 ('gustavo_fricke', 0.3721628785133362)]

## Analogías

Por otra parte, la analogía consiste en comparar 3 terminos mediante una operación del estilo: 

$$palabra1 - palabra2 \approx palabra 3 - x$$

para encontrar relaciones entre estos.

Por ejemplo:

| palabra 1 (pos) |  palabra 2 (neg) |
|-----------------|------------------|
|  macri          | piñera           |
| chile           |  x               |

In [32]:
biobio_w2v.wv.most_similar(positive=["bolsonaro", "argentina"], negative=['macri'], topn=3)

[('brasil', 0.46593397855758667),
 ('jair_bolsonaro', 0.4054754078388214),
 ('excapitán_ejército', 0.35641491413116455)]

In [33]:
biobio_w2v.wv.most_similar(positive=["chile", "huawei"], negative=['china'], topn=3)

[('walmart_chile', 0.2904326319694519),
 ('lipigas', 0.28741344809532166),
 ('empresa', 0.286331444978714)]

## Visualizar

Para visualizar, usaremos una técnica de reducción de dimensionalidad llamada [`T-SNE`](https://en.wikipedia.org/wiki/T-distributed_stochastic_neighbor_embedding)

Básicamente, ejecuta una reducción de dimensionalidad, que transforma las 300 dimensiones de los embeddings en 2.

In [ ]:
# Ejecutamos la transformación. Por lo general, demora una media hora mas o menos...
X_embedded = TSNE(n_components=2, verbose=True).fit_transform(
    biobio_w2v.wv[biobio_w2v.wv.vocab])

Extraemos la frecuencia de las palabras:

In [ ]:
word_counts = dict()
for item in biobio_w2v.wv.vocab:
    word_counts[item]=biobio_w2v.wv.vocab[item].count

Con los nuevos vectores que nos entrego TSNE mas el vocabulario y la frecuencia del vocabulario, formamos un DataFrame.


In [ ]:
tsne = pd.DataFrame({
    'x': X_embedded[:,0],
    'y': X_embedded[:,1],
    'vocab': list(biobio_w2v.wv.vocab.keys()) , 
    'count': list(word_counts.values())
})

**Guardar y Cargar TSNE**

In [34]:
#Guardar
#tsne.to_csv('./pretrained_models/biobio_w2v_tsne.csv', index= False, index_label=False)
# Cargar
#tsne = pd.read_csv('./pretrained_models/biobio_w2v_tsne.csv')


# Cargar desde github
tsne = pd.read_csv('https://github.com/dccuchile/CC6205/releases/download/Data/biobio_w2v_tsne.csv')



Ordenamos el Dataframe 

In [35]:
sorted_tsne = tsne.sort_values(by=['count'], ascending = False)

## Visualizamos

Para la visualización, usaremos plotly. Este nos deja tener una barra interactiva que nos mostrará las 100 palabras mas parecidas a la que escribimos.

In [36]:
tsne_sample = sorted_tsne.head(10000)

In [37]:
described_tsne = tsne_sample.describe()
min_y = described_tsne.y['min']
max_y = described_tsne.y['max']

min_x =  described_tsne.x['min']
max_x =  described_tsne.x['max']

In [ ]:
textbox = widgets.Text(description='Palabra:')

def validate(word):
    if word in tsne_sample.vocab.values:
        return True
    else:
        return False


def response(change):

    word = textbox.value.lower()
    
    if (word == ''):
        with fig.batch_update():
            fig.data[0].x = tsne_sample.x.values
            fig.data[0].y = tsne_sample.y.values
            fig.data[0].text = tsne_sample.vocab.values
    else :
        if validate(word):

            most_similar_words = [word]

            for word_tuple in biobio_w2v.wv.most_similar(positive=[word],topn = 100 ):
                if word_tuple[0] in tsne_sample.vocab.values:
                    most_similar_words.append(word_tuple[0])

            filtered_words = [word in most_similar_words for word in tsne_sample.vocab]
            temp = tsne_sample.loc[filtered_words]

            with fig.batch_update():
                fig.data[0].x = temp.x.values
                fig.data[0].y = temp.y.values
                fig.data[0].text = temp.vocab.values

In [ ]:
fig = go.FigureWidget(data=[
    go.Scatter(x=tsne_sample.x,
               y=tsne_sample.y,
               mode='markers',
               text=tsne_sample.vocab)
],
                      layout=go.Layout(title=go.layout.Title(
                          text="Visualización 2D Embeddings Biobio"),
                                       yaxis =dict(range=[min_y, max_y]),
                                       xaxis =dict(range=[min_x, max_x])
                                      ))

container = widgets.HBox([textbox])
textbox.observe(response, names="value")

widgets.VBox([container, fig])



## Word Embeddings como características para clasificar


En esta sección, veremos como utilizar los word embeddings como característica para **clasificar nuevamente el tópico de las noticias de la radio biobio**


Definimos el tokenizador (el mismo de antes):

In [38]:
def tokenizer(doc):
    preprocessed_doc = re.sub(r'[^\w\s+]', '', str(doc)).lower() 
    return [x.orth_ for x in nlp(preprocessed_doc)]

Luego, definimos como vamos a representar el documento. En este caso, haremos lo mismo que `BoW`.

Es decir, obtendremos la representación vectorial de cada palabra (ahora como vector continuo) y luego las sumaremos.


In [39]:
def get_doc_wv(wv, document, aggregation_function= np.sum):
    tokenized_document = tokenizer(document)
    selected_wv = []

    for token in tokenized_document:
        if token in wv.vocab:
            selected_wv.append(wv[token])

    selected_wv = np.array(selected_wv)
    return aggregation_function(selected_wv, axis=0)


In [40]:
# transformamos cada documento del dataset en la suma de los embeddings.
procesed_wv = np.array([get_doc_wv(biobio_w2v.wv, item) for item in data.content.values])

### Dividimos el dataset de embeddings en training y test

In [41]:
X_train, X_test, y_train, y_test = train_test_split(procesed_wv,
                                                    data.category,
                                                    test_size=0.33,
                                                    random_state=42)

### Entrenamos el clasificador

In [42]:
clf = LogisticRegression(random_state=0,
                         solver='saga',
                         multi_class='auto',
                         max_iter=5000,
                         n_jobs=4).fit(X_train, y_train)

### Predecimos y evaluamos: 

In [43]:
y_pred = clf.predict(X_test)

In [44]:
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

[[ 789   19  120   10   16]
 [  24 3205   38    2  120]
 [  87   29 3130   15   17]
 [  16    2   65  147    4]
 [  15  150   24    9  664]]


In [45]:
print(classification_report(y_test, y_pred))

               precision    recall  f1-score   support

     economia       0.85      0.83      0.84       954
internacional       0.94      0.95      0.94      3389
     nacional       0.93      0.95      0.94      3278
      opinion       0.80      0.63      0.71       234
     sociedad       0.81      0.77      0.79       862

     accuracy                           0.91      8717
    macro avg       0.87      0.83      0.84      8717
 weighted avg       0.91      0.91      0.91      8717



## En comparación con BoW

In [46]:
def classificate_with_bow(X_train, y_train, X_test, y_test):

    # Tokenizar y lematizar.
    def tokenizer_with_lemmatization(doc):
        return [x.lemma_ for x in nlp(doc)]

    # Definimos el vectorizador para convertir el texto a BoW:
    vectorizer = CountVectorizer(analyzer='word',
                                 tokenizer=tokenizer_with_lemmatization,
                                 
                                 ngram_range=(1, 1))

    # Definimos el clasificador que usaremos.
    clf = LogisticRegression(solver='saga',
                             multi_class='ovr',
                             max_iter=5000,
                             n_jobs=4)

    # Definimos el pipeline
    text_clf = Pipeline([('vect', vectorizer), ('clf', clf)])

    text_clf.fit(X_train, y_train)

    predicted = text_clf.predict(X_test)

    clf_report = classification_report(y_test, predicted)

    conf_matrix = confusion_matrix(y_test, predicted)
    print(clf_report, '\n\n', conf_matrix)

    return predicted, conf_matrix, clf_report

In [47]:
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(data.content,
                                                    data.category,
                                                    test_size=0.33,
                                                    random_state=42)




In [48]:
bow_pred, bow_conf_matrix, bow_clf_report = classificate_with_bow(X_train_2, y_train_2, X_test_2, y_test_2)

               precision    recall  f1-score   support

     economia       0.88      0.83      0.85       954
internacional       0.95      0.96      0.95      3389
     nacional       0.94      0.96      0.95      3278
      opinion       0.90      0.80      0.85       234
     sociedad       0.83      0.82      0.83       862

     accuracy                           0.93      8717
    macro avg       0.90      0.87      0.89      8717
 weighted avg       0.93      0.93      0.93      8717
 

 [[ 795   13  122    4   20]
 [  12 3242   33    0  102]
 [  80   32 3139   12   15]
 [   8    3   29  188    6]
 [  13  113   23    4  709]]


In [49]:
print(bow_clf_report)

               precision    recall  f1-score   support

     economia       0.88      0.83      0.85       954
internacional       0.95      0.96      0.95      3389
     nacional       0.94      0.96      0.95      3278
      opinion       0.90      0.80      0.85       234
     sociedad       0.83      0.82      0.83       862

     accuracy                           0.93      8717
    macro avg       0.90      0.87      0.89      8717
 weighted avg       0.93      0.93      0.93      8717

