# Markdown

Esta es una celda de texto.

# Esto es un titulo grandote

## Esto es un titulo un poco menos grandote


Esto es un parrafo, `esto esta en codigo`, **esto esta en negrita**, *esto esta en cursiva*

Se puede insertar codigo multilinea tambien.
```java
public static void main(String args[]) { 
    System.out.println("wena");
} 
```


Se pueden insertar lineas para separar texto

---

Se pueden insertar tablas!

| Esto      | Es   | Una  | Tabla   | !!      |
|-----------|------|------|---------|---------|
| 1         | 2    | hola | chao    | un dato |
| otro dato | pero | mira | cuantos | datos   |



Se puede "citar" texto usando cabezas de pescado
> Esta es una frase celebre de algun famoso
>
> -- Albert Einstein

Tambien se puede insertar formulas de $\LaTeX$ dentro del mismo texto: $a = \frac{e^y\sqrt{x+2}}{x^2}$. Se puede insertar $\LaTeX$ en general tambien.


\begin{equation}
\it{CE}(p,q)=\sum_{x}p(x)\log \bigg(\frac{1}{q(x)}\bigg)=- \sum_{x}p(x)\log q(x)
\end{equation}

Tambien se puede escribir `html`.

<strong> Esto esta en negrita usando html </strong>

Aca dejo mas recursos sobre Markdown, Colab y Jupyter Notebook:
* https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax
* https://colab.research.google.com/notebooks/intro.ipynb
* https://jupyter.org/
* https://nbviewer.jupyter.org/github/ipython/ipython/blob/1.x/examples/notebooks/Cell%20Magics.ipynb

# Pequeña introduccion a Numpy y Pandas

Colab viene con muchas librerias preinstaldas. Dentro de las que mas vamos a usar estan Numpy y Pandas. Aca tambien dejo unas "cheat sheets" para ambas bibliotecas.
* https://pandas.pydata.org/docs/
* https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf
* https://numpy.org/doc/1.18/
* https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf



In [1]:
import numpy as np
import pandas as pd

In [2]:
a = list(range(10))
a
b = []
for e in a:
    b.append(e**2)
print(b)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


## Numpy
Paquete fundamental para computacion matematica.

Clase principal: arraglo n-dimensional, ndarray

In [3]:
# Como crear arreglos

# A partir de otro una lista de python
print(np.array(range(10)), "\n")

# Un arrelo de enteros entre un rango un paso especifico
print(np.arange(3, 20, 2), "\n")

# Un arreglo con 10 numero entre 1 y 2
print(np.linspace(1,2,10), "\n")

# Un arreglo de puros 0
print(np.zeros(10), "\n")

[0 1 2 3 4 5 6 7 8 9] 

[ 3  5  7  9 11 13 15 17 19] 

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ] 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 



In [29]:
np.zeros((4,5,3))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [0]:
# arreglos de mas dimensiones
print(np.arange(20).reshape(4,5))
print("=" * 20)
print(np.arange(60).reshape(3,4,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [0]:
# Operaciones sobre arreglos
a = np.arange(10)

In [0]:
a**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [0]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [0]:
np.pi**a

array([1.00000000e+00, 3.14159265e+00, 9.86960440e+00, 3.10062767e+01,
       9.74090910e+01, 3.06019685e+02, 9.61389194e+02, 3.02029323e+03,
       9.48853102e+03, 2.98090993e+04])

In [0]:
b = np.arange(5,15)
a + b

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [0]:
a * b

array([  0,   6,  14,  24,  36,  50,  66,  84, 104, 126])

In [0]:
a @ b.T

510

In [33]:
a = np.arange(12).reshape(3,4)
a.sum(axis=1)

array([ 6, 22, 38])

In [34]:
# Slicing
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [35]:
a[0]

array([0, 1, 2, 3])

In [0]:
a[1, :]

array([4, 5, 6, 7])

In [0]:
a[2, 3]

11

In [0]:
a[2, 0::2]

array([ 8, 10])

In [44]:
type(a)

numpy.ndarray

In [56]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [54]:
b = np.arange(10*6).reshape(6,10)
b


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [55]:
b + a

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [10, 12, 14, 16, 18, 20, 22, 24, 26, 28],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [30, 32, 34, 36, 38, 40, 42, 44, 46, 48],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [50, 52, 54, 56, 58, 60, 62, 64, 66, 68]])

## Pandas
Una herramienta para hacer analisis y manipulacion de datos.

In [4]:
# Leer datos en distintos formatos usando las funciones read_*
# El objeto principal es el DataFrame
dataset = pd.read_json(
    'https://github.com/dccuchile/CC6205/releases/download/Data/biobio_nacional.json'
)
print(type(dataset))
print(dataset.shape)
dataset.head()

<class 'pandas.core.frame.DataFrame'>
(200, 11)


publication_date publication_hour             author  \
0       05/08/2019            10:50  Gonzalo Cifuentes   
1       05/08/2019            07:51     Felipe Delgado   
2       05/08/2019            08:14      Nicolás Parra   
3       05/08/2019            08:19      Catalina Díaz   
4       05/08/2019            08:27      Catalina Díaz   

                   author_link  \
0    /lista/autores/gcifuentes   
1      /lista/autores/fdelgado   
2        /lista/autores/nparra   
3  /lista/autores/catalinadiaz   
4  /lista/autores/catalinadiaz   

                                               title  \
0  ¿Lavar la ropa con luz?: invento de chilenos e...   
1  Alrededor de 40 mil hogares de Puente Alto, Pi...   
2  Habla director de Compin Bío Bío que se autoap...   
3  6 damnificados dejó incendio que destruyó una ...   
4  Con arresto domiciliario quedó menor detenido ...   

                                                link  category  \
0  https://www.biobiochile.cl/noticias/nacional/c...  Nacional   
1  https://www.biobiochile.cl/noticias/nacional/r...  Nacional   
2  https://www.biobiochile.cl/noticias/nacional/r...  Nacional   
3  https://www.biobiochile.cl/noticias/nacional/r...  Nacional   
4  https://www.biobiochile.cl/noticias/nacional/r...  Nacional   

            subcategory                                            content  \
0              Nacional    Alumnos de Ingeniería de la Universidad Cató...   
1  Región Metropolitana    Alrededor de 40 mil hogares de las comunas d...   
2    Región del Bío Bío    Quien fuera el director de la Compin Bío Bío...   
3    Región de los Ríos    Seis damnificados es el saldo de un incendio...   
4   Región de los Lagos    Con arresto domiciliario total quedó el adol...   

                                                tags  \
0  [#Chile, #Ingeniería UC, #LightWash, #Luz, #Se...   
1  [#Pirque, #Puente Alto, #Región Metropolitana,...   
2  [#Compin, #Concepción, #Licencia, #Region del ...   
3  [#Bomberos, #Damnificados, #Daños, #Incendio, ...   
4  [#Arresto Domiciliario, #Bullying, #Calbuco, #...   

                                      embedded_links  
0                                                 []  
1                                                 []  
2  [https://media.biobiochile.cl/wp-content/uploa...  
3  [https://media.biobiochile.cl/wp-content/uploa...  
4  [https://media.biobiochile.cl/wp-content/uploa...

In [59]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 11 columns):
publication_date    200 non-null object
publication_hour    200 non-null object
author              200 non-null object
author_link         200 non-null object
title               200 non-null object
link                200 non-null object
category            200 non-null object
subcategory         200 non-null object
content             200 non-null object
tags                200 non-null object
embedded_links      200 non-null object
dtypes: object(11)
memory usage: 17.3+ KB


In [0]:
# Obtener toda una columna
authors = dataset["author"]
print("tipo: ", type(authors))
print(authors.head())
print(authors.shape)

tipo:  <class 'pandas.core.series.Series'>
0    Gonzalo Cifuentes
1       Felipe Delgado
2        Nicolás Parra
3        Catalina Díaz
4        Catalina Díaz
Name: author, dtype: object
(200,)


In [0]:
# Seleccionar multiples columnas
dataset[["publication_date", "category"]].head()

publication_date  category
0       05/08/2019  Nacional
1       05/08/2019  Nacional
2       05/08/2019  Nacional
3       05/08/2019  Nacional
4       05/08/2019  Nacional

In [0]:
# Seleccionar subconjunto de filas
mask = dataset["subcategory"] == "Nacional"
print(mask.head(), "\n")

dataset[mask].head()


0     True
1    False
2    False
3    False
4    False
Name: subcategory, dtype: bool 



publication_date  ...                                     embedded_links
0        05/08/2019  ...                                                 []
6        05/08/2019  ...                                                 []
11       05/08/2019  ...                                                 []
14       05/08/2019  ...  [https://media.biobiochile.cl/wp-content/uploa...
16       05/08/2019  ...  [https://media.biobiochile.cl/wp-content/uploa...

[5 rows x 11 columns]

In [61]:
# loc/iloc, loc on labels, iloc con indices
dataset.loc[dataset["subcategory"] == "Región de los Lagos", ["author", "link"]]

author                                               link
4            Catalina Díaz  https://www.biobiochile.cl/noticias/nacional/r...
22            Nicolás Díaz  https://www.biobiochile.cl/noticias/nacional/r...
50   María José Villarroel  https://www.biobiochile.cl/noticias/nacional/r...
55           Sandar Oporto  https://www.biobiochile.cl/noticias/nacional/r...
59           Sandar Oporto  https://www.biobiochile.cl/noticias/nacional/r...
63             Matías Vega  https://www.biobiochile.cl/noticias/nacional/r...
76   María José Villarroel  https://www.biobiochile.cl/noticias/nacional/r...
82           Nicolás Parra  https://www.biobiochile.cl/noticias/nacional/r...
89             Matías Vega  https://www.biobiochile.cl/noticias/nacional/r...
105     Valentina González  https://www.biobiochile.cl/noticias/nacional/r...
124     Valentina González  https://www.biobiochile.cl/noticias/nacional/r...
128         Manuel Stuardo  https://www.biobiochile.cl/noticias/nacional/r...
131       Yessenia Márquez  https://www.biobiochile.cl/noticias/nacional/r...
143       Yessenia Márquez  https://www.biobiochile.cl/noticias/nacional/r...
152         Manuel Stuardo  https://www.biobiochile.cl/noticias/nacional/r...
154           Nicolás Díaz  https://www.biobiochile.cl/noticias/nacional/r...
157         Manuel Stuardo  https://www.biobiochile.cl/noticias/nacional/r...
169       Yessenia Márquez  https://www.biobiochile.cl/noticias/nacional/r...
184       Yessenia Márquez  https://www.biobiochile.cl/noticias/nacional/r...
190     Valentina González  https://www.biobiochile.cl/noticias/nacional/r...
191          Nicolás Parra  https://www.biobiochile.cl/noticias/nacional/r...
195            Matías Vega  https://www.biobiochile.cl/noticias/nacional/r...

In [63]:
dataset.iloc[20:30:2, [1, 3, 4]]

publication_hour  ...                                              title
20            00:57  ...  Detienen a conductor en Coronel tras ofrecer $...
22            21:33  ...  Puerto Montt implementará plan de contingencia...
24            22:00  ...  Mañalich y Comisión de Salud analizarán este l...
26            23:16  ...  En prisión preventiva queda exfuncionario de l...
28            23:49  ...  Automóvil y bus del Transantiago protagonizan ...

[5 rows x 3 columns]

# NLTK
NLTK (Natural Language Processing Kit) es una libreria de procesamiento de lenguaje natural. Ofrece utilidades como tokenizacion, lemmatization, stemming,etc.


In [64]:
import nltk
nltk.download("all")


[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package biocreative_ppi is already up-to-date!
[nltk_data]    | Downloading package brown to /root/nltk_data...
[nltk_data]    |   Package brown is already up-to-date!
[nltk_data]    | Downloading package brown_tei to /root/nltk_data...
[nltk_data]    |   Package brown_tei is already up-to-date!
[nltk_data]    | Downloading package cess_cat to /root/nltk_data...
[nltk_data]    |   Package cess_cat is already up-to-date!
[nltk_data]    | Downloading package cess_esp to /root/nltk_data...
[nltk_data]    |   Package cess_esp is already up-to-date!
[nltk_data]    | Downloading packag

True

In [5]:
# tokenizacion
from nltk import word_tokenize
s = "Hola como están, esta es una frase en español."

word_tokenize(s, language="spanish")

LookupError: 
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt/PY3/spanish.pickle

  Searched in:
    - '/home/fbravo/nltk_data'
    - '/home/fbravo/anaconda3/nltk_data'
    - '/home/fbravo/anaconda3/share/nltk_data'
    - '/home/fbravo/anaconda3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - ''
**********************************************************************


In [6]:
# stemming
from nltk.stem import SnowballStemmer

stemmer = SnowballStemmer("spanish")
print(stemmer.stem("perros"))
stemmer.stem("perros") == stemmer.stem("perro")

perr


True

In [7]:
# lemmatization, no pille lemmatizer de nltk en espannol
from nltk.stem import WordNetLemmatizer, PorterStemmer

stemmer = PorterStemmer()
print(stemmer.stem("houses"))

wnl = WordNetLemmatizer()
print(wnl.lemmatize("houses"))

hous


LookupError: 
**********************************************************************
  Resource wordnet not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('wordnet')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/wordnet

  Searched in:
    - '/home/fbravo/nltk_data'
    - '/home/fbravo/anaconda3/nltk_data'
    - '/home/fbravo/anaconda3/share/nltk_data'
    - '/home/fbravo/anaconda3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


# Datos
Aca voy a mostrar como acceder a datos desde colab.


Una forma super simple es conectarse a su Drive y desde ahi acceder a los datos

In [15]:
# Esto no corre en local
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
df = pd.read_csv("drive/My Drive/2018_emol_comments_small.tsv", delimiter="\t")
df.head()

idNoticia  idComment  creatorId  ...  denounces           time level
0     892722    4799147     160736  ...          0  1516963115000     0
1     892722    4798886       7823  ...          0  1516960895000     0
2     892722    4798914     245784  ...          0  1516961099000     1
3     892722    4798783      65076  ...          0  1516959790000     0
4     892722    4798175      11263  ...          0  1516951826000     0

[5 rows x 12 columns]

Usando la habilidad de colab de ejecutar comandos de shell desde una celda de codigo, podemos descargar un dataset usando la linea de comando, ya sea con `wget` o `curl`.

In [69]:
!wget users.dcc.uchile.cl/~gchapero/datasets/2018_emol_comments_small.tsv

--2020-03-26 18:53:44--  http://users.dcc.uchile.cl/~gchapero/datasets/2018_emol_comments_small.tsv
Resolving users.dcc.uchile.cl (users.dcc.uchile.cl)... 200.9.99.211, 192.80.24.4
Connecting to users.dcc.uchile.cl (users.dcc.uchile.cl)|200.9.99.211|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://users.dcc.uchile.cl/~gchapero/datasets/2018_emol_comments_small.tsv [following]
--2020-03-26 18:53:44--  https://users.dcc.uchile.cl/~gchapero/datasets/2018_emol_comments_small.tsv
Connecting to users.dcc.uchile.cl (users.dcc.uchile.cl)|200.9.99.211|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11115406 (11M) [text/tab-separated-values]
Saving to: ‘2018_emol_comments_small.tsv’

2018_emol_comments_ 100%[===================>]  10.60M  4.67MB/s    in 2.3s    

2020-03-26 18:53:47 (4.67 MB/s) - ‘2018_emol_comments_small.tsv’ saved [11115406/11115406]



In [70]:
df = pd.read_csv("2018_emol_comments_small.tsv", delimiter="\t")
df.head()

idNoticia  idComment  creatorId  ...  denounces           time level
0     892722    4799147     160736  ...          0  1516963115000     0
1     892722    4798886       7823  ...          0  1516960895000     0
2     892722    4798914     245784  ...          0  1516961099000     1
3     892722    4798783      65076  ...          0  1516959790000     0
4     892722    4798175      11263  ...          0  1516951826000     0

[5 rows x 12 columns]