In [10]:
!

sample_data


Esta es una celda de texto.

# Esto es un titulo grandote

## Esto es un titulo un poco menos grandote


Esto es un parrafo, `esto esta en codigo`, **esto esta en negrita**, *esto esta en cursiva*

Se puede insertar codigo multilinea tambien.
```java
public static void main(String args[]) { 
    System.out.println("wena");
} 
```

Se pueden insertar lineas para separar texto

---

Tambien se puede insertar formulas de $\LaTeX$ dentro del mismo texto: $a = \frac{e^y\sqrt{x+2}}{x^2}$. Se puede insertar $\LaTeX$ en general tambien.


\begin{equation}
\it{CE}(p,q)=\sum_{x}p(x)\log \bigg(\frac{1}{q(x)}\bigg)=- \sum_{x}p(x)\log q(x)
\end{equation}

Tambien se puede escribir `html`.

<strong> Esto esta en negrita usando html </strong>

Aca dejo mas recursos sobre Colab y Jupyter Notebook:
* https://colab.research.google.com/notebooks/intro.ipynb
* https://jupyter.org/
* https://nbviewer.jupyter.org/github/ipython/ipython/blob/1.x/examples/notebooks/Cell%20Magics.ipynb

# Pequeña introduccion a Numpy y Pandas

Colab viene con muchas librerias preinstaldas. Dentro de las que mas vamos a usar estan Numpy y Pandas. Aca tambien dejo unas "cheat sheets" para ambas bibliotecas.
* https://pandas.pydata.org/docs/
* https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf
* https://numpy.org/doc/1.18/
* https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf



In [0]:
import numpy as np
import pandas as pd

## Pandas
Una herramienta para hacer analisis y manipulacion de datos.

In [0]:
# El objeto principal es el DataFrame
dataset = pd.read_json(
    'https://github.com/dccuchile/CC6205/releases/download/Data/biobio_nacional.json'
)
print(type(dataset))
dataset.head()

<class 'pandas.core.frame.DataFrame'>


publication_date  ...                                     embedded_links
0       05/08/2019  ...                                                 []
1       05/08/2019  ...                                                 []
2       05/08/2019  ...  [https://media.biobiochile.cl/wp-content/uploa...
3       05/08/2019  ...  [https://media.biobiochile.cl/wp-content/uploa...
4       05/08/2019  ...  [https://media.biobiochile.cl/wp-content/uploa...

[5 rows x 11 columns]

In [0]:
# Obtener toda una columna
print("tipo: ", type(dataset["author"]))
print(dataset["author"].head())

tipo:  <class 'pandas.core.series.Series'>
0    Gonzalo Cifuentes
1       Felipe Delgado
2        Nicolás Parra
3        Catalina Díaz
4        Catalina Díaz
Name: author, dtype: object


In [0]:
# Obtener una fila
dataset.iloc[0]

publication_date                                           05/08/2019
publication_hour                                                10:50
author                                              Gonzalo Cifuentes
author_link                                 /lista/autores/gcifuentes
title               ¿Lavar la ropa con luz?: invento de chilenos e...
link                https://www.biobiochile.cl/noticias/nacional/c...
category                                                     Nacional
subcategory                                                  Nacional
content               Alumnos de Ingeniería de la Universidad Cató...
tags                [#Chile, #Ingeniería UC, #LightWash, #Luz, #Se...
embedded_links                                                     []
Name: 0, dtype: object

## Numpy
Paquete fundamental para computacion matematica.

Clase principal: arraglo n-dimensional, ndarray

In [0]:
# Como crear arreglos

# A partir de otro una lista de python
print(np.array(range(10)))

# Un arrelo de enteros entre un rango un paso especifico
print(np.arange(3, 20, 2))

# Un arreglo con 10 numero entre 1 y 2
print(np.linspace(1,2,10))

# Un arreglo de puros 0
print(np.zeros(10))

[0 1 2 3 4 5 6 7 8 9]
[ 3  5  7  9 11 13 15 17 19]
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2. ]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [0]:
# Operaciones sobre arreglos

a = np.arange(10)
print(a**2)
print(np.sqrt(a))
print(np.pi**a)

b = np.arange(5, 15)
print(a + b)
print(a * b)

[ 0  1  4  9 16 25 36 49 64 81]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 3.14159265e+00 9.86960440e+00 3.10062767e+01
 9.74090910e+01 3.06019685e+02 9.61389194e+02 3.02029323e+03
 9.48853102e+03 2.98090993e+04]
[ 5  7  9 11 13 15 17 19 21 23]
[  0   6  14  24  36  50  66  84 104 126]


In [0]:
# arreglos de mas dimensiones
print(np.arange(20).reshape(4,5))
print("=" * 20)
print(np.arange(60).reshape(3,4,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


# Datos
Aca voy a mostrar como acceder a datos desde colab.


Una forma super simple es conectarse a su Drive y desde ahi acceder a los datos

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
df = pd.read_csv("drive/My Drive/2018_emol_comments_small.tsv", delimiter="\t")
df.head()

idNoticia  idComment  creatorId  ...  denounces           time level
0     892722    4799147     160736  ...          0  1516963115000     0
1     892722    4798886       7823  ...          0  1516960895000     0
2     892722    4798914     245784  ...          0  1516961099000     1
3     892722    4798783      65076  ...          0  1516959790000     0
4     892722    4798175      11263  ...          0  1516951826000     0

[5 rows x 12 columns]

Usando la habilidad de colab de ejecutar comandos de shell desde una celda de codigo, podemos descargar un dataset usando la linea de comando, ya sea con `wget` o `curl`.

In [0]:
!wget users.dcc.uchile.cl/~gchapero/datasets/2018_emol_comments_small.tsv

In [0]:
df = pd.read_csv("2018_emol_comments_small.tsv", delimiter="\t")
df.head()

--2020-03-22 23:01:33--  http://users.dcc.uchile.cl/~gchapero/datasets/2018_emol_comments_small.tsv
Resolving users.dcc.uchile.cl (users.dcc.uchile.cl)... 200.9.99.211, 192.80.24.4
Connecting to users.dcc.uchile.cl (users.dcc.uchile.cl)|200.9.99.211|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://users.dcc.uchile.cl/~gchapero/datasets/2018_emol_comments_small.tsv [following]
--2020-03-22 23:01:34--  https://users.dcc.uchile.cl/~gchapero/datasets/2018_emol_comments_small.tsv
Connecting to users.dcc.uchile.cl (users.dcc.uchile.cl)|200.9.99.211|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11115406 (11M) [text/tab-separated-values]
Saving to: ‘2018_emol_comments_small.tsv.3’

2018_emol_comments_ 100%[===================>]  10.60M  3.66MB/s    in 2.9s    

2020-03-22 23:01:38 (3.66 MB/s) - ‘2018_emol_comments_small.tsv.3’ saved [11115406/11115406]



idNoticia  idComment  creatorId  ...  denounces           time level
0     892722    4799147     160736  ...          0  1516963115000     0
1     892722    4798886       7823  ...          0  1516960895000     0
2     892722    4798914     245784  ...          0  1516961099000     1
3     892722    4798783      65076  ...          0  1516959790000     0
4     892722    4798175      11263  ...          0  1516951826000     0

[5 rows x 12 columns]